[package]
name = "fastq_checker"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
flate2 = "1.0.26"
rust-htslib = "0.46.0"
